Confirm pt autotranslated definitions.
De7vID/klingon-assistant-data pull request #427
Opened 2020-10-22 07:27 UTC by dlyongemallo

2020-10-22 07:32 UTC, De7vID commented
@thiagocmatos Are these good? Any edits?

2020-11-10 20:41 UTC, thiagocmatos requested changes
I have proposed two updates.

2020-11-10 20:41 UTC, thiagocmatos commented on mem-28-examples.xml
> +      <column name="definition_pt">A guerra de maldições definitivamente começou.</column>
Better update to:
A guerra de insultos definitivamente começou.

2020-11-10 20:41 UTC, thiagocmatos commented on mem-28-examples.xml
> +      <column name="definition_pt">Demitido!</column>
Better change to:
Dispensado!

2020-11-11 08:50 UTC, merged